# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-26 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0014_courseoverview_certificate_available_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='downloadable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='external_product_link',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='product',
            field=models.BooleanField(default=False),
        ),
    ]
