# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-20 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_overviews', '0014_courseoverview_certificate_available_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebScienceCourseOverview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=7)),
                ('image', models.CharField(max_length=254)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='web_science', to='course_overviews.CourseOverview')),
            ],
            options={
                'verbose_name': 'Course settings',
                'verbose_name_plural': 'Course settings',
            },
        ),
    ]
