# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-27 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_science', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websciencecourseoverview',
            name='main_image',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
