# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-21 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_science', '0002_websciencecourseoverview_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websciencecourseoverview',
            name='main_image',
        ),
    ]
