# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-05 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=b'')),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True, help_text='If you want to add an URL to your message, paste it here.', max_length=255, null=True)),
                ('is_published', models.BooleanField(default=False, help_text='Set this value to True if you want this slide to be shown on Homepage')),
                ('slide_order', models.PositiveIntegerField(help_text='Use integers to set an order of appearance for your slides. 1 goes first.')),
            ],
            options={
                'ordering': ['slide_order'],
            },
        ),
        migrations.CreateModel(
            name='HomepageVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(help_text="Add or edit link for the video. <b>Important</b>: insert only a link, without iframe width, height, frameborder or any other attributes. Click <a href='https://support.google.com/youtube/answer/171780'>here</a> to see how to embed Youtube video or playlist. Click <a href='https://help.vimeo.com/hc/en-us/articles/360000710167-Accessing-and-editing-embed-codes'>here</a> to see how to embed Vimeo video. Your link should be playable directly from the browser. <b>Example:</b> https://www.youtube.com/embed/videoseries?list=PLx0sYbCqOb8TBPRdmBHs5Iftvv9TPboYG.", max_length=255)),
            ],
        ),
    ]
