# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-02 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_overviews', '0014_courseoverview_certificate_available_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, upload_to=b'course_category')),
                ('enabled', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('courses', models.ManyToManyField(to='course_overviews.CourseOverview')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='course_category.CourseCategory')),
            ],
            options={
                'verbose_name_plural': 'Course Categories',
            },
        ),
    ]
