# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-16 12:55
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='courses',
            field=jsonfield.fields.JSONField(default=[]),
        ),
    ]
