# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-01 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0015_auto_20190926_0939'),
        ('course_category', '0002_program_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='products',
            field=models.ManyToManyField(to='course_overviews.CourseOverview'),
        ),
    ]
