# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-01-15 14:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_groups', '0003_auto_20170609_1455'),
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cohortassigment',
            unique_together=set([('cohort', 'user')]),
        ),
    ]
