# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-28 11:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hcspecialization', '0001_initial'),
        ('specialization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='extrafields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=255)),
                ('rcountry', models.CharField(blank=True, db_index=True, max_length=255)),
                ('rstate', models.CharField(blank=True, db_index=True, max_length=255)),
                ('rcity', models.CharField(blank=True, db_index=True, max_length=255)),
                ('address', models.CharField(blank=True, db_index=True, max_length=255)),
                ('rpincode', models.CharField(blank=True, db_index=True, max_length=6)),
                ('reg_num', models.CharField(max_length=100, verbose_name=b'Reg Num')),
                ('user_type', models.CharField(choices=[(b'dr', b'Doctor'), (b'u', b'User'), (b'ms', b'Medical Student'), (b'hc', b'Health Care Proffessional')], db_index=True, default=b'dr', max_length=2)),
                ('hcspecialization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hcspecialization.hcspecializations')),
                ('specialization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='specialization.specializations')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extrafields', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
