# Generated by Django 4.2.18 on 2025-03-05 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oel_components', '0003_remove_componentversioncontent_learner_downloadable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseToLibraryImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField(auto_now_add=True)),
                ('state', models.CharField(max_length=100)),
                ('course_ids', models.TextField(help_text='Whitespace-separated list of course keys for which to compute grades.')),
                ('library_key', models.CharField(max_length=100)),
                ('source_type', models.CharField(max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComponentVersionImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('source_usage_key', opaque_keys.edx.django.models.UsageKeyField(max_length=255)),
                ('component_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oel_components.componentversion')),
                ('library_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_to_library_import.coursetolibraryimport')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
