# Generated by Django 4.2.18 on 2025-02-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseToLibraryImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('state', models.CharField(max_length=100)),
                ('course_id', models.CharField(max_length=100)),
                ('library_key', models.CharField(max_length=100)),
                ('source_type', models.CharField(max_length=30)),
            ],
        ),
    ]
