# Generated by Django 4.2.18 on 2025-03-27 22:54

import cms.djangoapps.course_to_library_import.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import opaque_keys.edx.django.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content_libraries', '0011_remove_contentlibrary_bundle_uuid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oel_components', '0003_remove_componentversioncontent_learner_downloadable'),
        ('oel_publishing', '0003_containers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseToLibraryImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('imported', 'Imported'), ('error', 'Error')], default='pending', max_length=100)),
                ('course_ids', models.TextField(help_text='Whitespace-separated list of course keys for which to compute grades.', validators=[cms.djangoapps.course_to_library_import.validators.validate_course_ids])),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('content_library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_to_library_imports', to='content_libraries.contentlibrary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course to Library Import',
                'verbose_name_plural': 'Course to Library Imports',
            },
        ),
        migrations.CreateModel(
            name='ContainerVersionImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('source_usage_key', opaque_keys.edx.django.models.UsageKeyField(max_length=255)),
                ('container_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oel_publishing.containerversion')),
                ('library_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_to_library_import.coursetolibraryimport')),
            ],
            options={
                'verbose_name': 'Container Version Import',
                'verbose_name_plural': 'Container Version Imports',
            },
        ),
        migrations.CreateModel(
            name='ComponentVersionImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('source_usage_key', opaque_keys.edx.django.models.UsageKeyField(max_length=255)),
                ('component_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oel_components.componentversion')),
                ('library_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_to_library_import.coursetolibraryimport')),
            ],
            options={
                'verbose_name': 'Component Version Import',
                'verbose_name_plural': 'Component Version Imports',
            },
        ),
    ]
