# Generated by Django 4.2.18 on 2025-03-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_to_library_import', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetolibraryimport',
            options={'verbose_name': 'Course to Library Import', 'verbose_name_plural': 'Course to Library Imports'},
        ),
        migrations.AddField(
            model_name='coursetolibraryimport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('IMPORTED', 'Imported'), ('ERROR', 'Error')], default='PENDING', max_length=100),
        ),
    ]
