# Generated by Django 4.2.18 on 2025-02-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_to_library_import', '0002_coursetolibraryimport_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetolibraryimport',
            name='metadata',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
