# Generated by Django 4.2.18 on 2025-03-06 17:34

import cms.djangoapps.course_to_library_import.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_to_library_import', '0002_alter_coursetolibraryimport_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componentversionimport',
            options={'verbose_name': 'Component Version Import', 'verbose_name_plural': 'Component Version Imports'},
        ),
        migrations.RemoveField(
            model_name='coursetolibraryimport',
            name='date',
        ),
        migrations.RemoveField(
            model_name='coursetolibraryimport',
            name='state',
        ),
        migrations.AlterField(
            model_name='coursetolibraryimport',
            name='course_ids',
            field=models.TextField(help_text='Whitespace-separated list of course keys for which to compute grades.', validators=[cms.djangoapps.course_to_library_import.validators.validate_course_ids]),
        ),
        migrations.AlterField(
            model_name='coursetolibraryimport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('imported', 'Imported'), ('error', 'Error')], default='pending', max_length=100),
        ),
    ]
