# Generated by Django 4.2.18 on 2025-02-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_to_library_import', '0003_alter_coursetolibraryimport_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetolibraryimport',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
