// title
export const TITLE_CHANGED = 'TITLE_CHANGED';
// questions
export const QUESTION_CHANGED = 'QUESTION_CHANGED';
export const QUESTION_ADDED = 'QUESTION_ADDED';
export const QUESTION_DELETED = 'QUESTION_DELETED';

// Introduction
export const INTRODUCTION_CHANGED = 'INTRODUCTION_CHANGED';
export const INTRODUCTION_LOADED = 'INTRODUCTION_LOADED';
export const INTRODUCTION_NEW = 'INTRODUCTION_NEW';
export const INTRODUCTION_ADD_CONTENT = 'INTRODUCTION_ADD_CONTENT';
export const INTRODUCTION_REMOVE_CONTENT = 'INTRODUCTION_REMOVE_CONTENT';
export const INTRODUCTION_IMAGE_ADD = 'INTRODUCTION_IMAGE_ADD';
export const INTRODUCTION_IMAGE_CHANGED = 'INTRODUCTION_IMAGE_CHANGED';
export const INTRODUCTION_IMAGE_REMOVE = 'INTRODUCTION_IMAGE_REMOVE';

// Simulation
export const SIMULATION_CHANGED = 'SIMULATION_CHANGED';
export const SIMULATION_LOADED = 'SIMULATION_LOADED';
export const SIMULATION_NEW = 'SIMULATION_NEW';
export const SIMULATION_ADD_CONTENT = 'SIMULATION_ADD_CONTENT';
export const SIMULATION_REMOVE_CONTENT = 'SIMULATION_REMOVE_CONTENT';
export const SIMULATION_IMAGE_ADD = 'SIMULATION_IMAGE_ADD';
export const SIMULATION_IMAGE_CHANGED = 'SIMULATION_IMAGE_CHANGED';
export const SIMULATION_IMAGE_REMOVE = 'SIMULATION_IMAGE_REMOVE';



// subsection data

export const SUBSECTION_DATA_CHANGED = 'SUBSECTION_DATA_CHANGED';
