// title
export const TITLE_CHANGED = 'TITLE_CHANGED';
// questions
export const QUESTION_CHANGED = 'QUESTION_CHANGED';
export const QUESTION_ADDED = 'QUESTION_ADDED';
export const QUESTION_DELETED = 'QUESTION_DELETED';

// Introduction
export const INTRODUCTION_CHANGED = 'INTRODUCTION_CHANGED';
export const INTRODUCTION_LOADED = 'INTRODUCTION_LOADED';
export const INTRODUCTION_NEW = 'INTRODUCTION_NEW';

// Simulation
export const SIMULATION_CHANGED = 'SIMULATION_CHANGED';
export const SIMULATION_LOADED = 'SIMULATION_LOADED';
export const SIMULATION_NEW = 'SIMULATION_NEW';



// subsection data

export const SUBSECTION_DATA_CHANGED = 'SUBSECTION_DATA_CHANGED';
