// title
export const TITLE_CHANGED = 'TITLE_CHANGED';
// questions
export const QUESTION_CHANGED = 'QUESTION_CHANGED';
export const QUESTION_ADDED = 'QUESTION_ADDED';
export const QUESTION_DELETED = 'QUESTION_DELETED';
// Introduction

export const INTRODUCTION_CHANGED = 'INTRODUCTION_CHANGED';
