# Generated by Django 4.2.20 on 2025-05-09 13:55

from django.db import migrations, models
import django.db.models.deletion


def set_status_to_null(apps, schema_editor):
    """
    Set status to null for all existing Import instances.
    """
    Import = apps.get_model('import_from_modulestore', 'Import')

    # Update all Import instances to set status to null
    Import.objects.update(status=None)


class Migration(migrations.Migration):

    dependencies = [
        ('user_tasks', '0004_url_textfield'),
        ('import_from_modulestore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='import',
            name='created',
        ),
        migrations.RemoveField(
            model_name='import',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='import',
            name='uuid',
        ),
        migrations.RunPython(set_status_to_null, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='import',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_tasks.usertaskstatus'),
        ),
    ]
