# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-28 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'name')),
                ('emailid', models.CharField(db_index=True, max_length=255)),
                ('message', models.CharField(blank=True, max_length=3000, null=True)),
                ('inquiry_type', models.CharField(db_index=True, max_length=2)),
                ('phone', models.CharField(db_index=True, max_length=13)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
