# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-03-04 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0014_change_eligible_certs_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='organization',
            field=models.CharField(blank=True, help_text='Organization name of template.Used if organization id is not set.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='organization_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Organization id of template.', null=True),
        ),
    ]
