# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-10 13:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Onboarding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_1', models.TextField(blank=True, verbose_name='First Page')),
                ('page_2', models.TextField(blank=True, verbose_name='Second Page')),
                ('page_3', models.TextField(blank=True, verbose_name='Third Page')),
                ('page_4', models.TextField(blank=True, verbose_name='Fourth Page')),
            ],
        ),
        migrations.CreateModel(
            name='UserOnboarding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_1', models.BooleanField(default=False)),
                ('page_2', models.BooleanField(default=False)),
                ('page_3', models.BooleanField(default=False)),
                ('page_4', models.BooleanField(default=False)),
                ('onboarding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hera.Onboarding')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
