# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-13 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0014_courseoverview_certificate_available_date'),
        ('hera', '0002_remove_useronboarding_onboarding'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCourseSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_overviews.CourseOverview')),
            ],
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='page_1',
            field=models.TextField(blank=True, default='<div class="onboarding-holder">\n    <div class="onboarding-content">\n        <h1>\n            Hi! Welcome to HERA.\n        </h1>\n        <div class="onboarding-text-block">\n            <h3>\n                What is HERA?\n            </h3>\n            <p>\n                The HERA system is designed to help you learn scientific thinking skills in an easy and engaging way.\n            </p>\n        </div>\n        <div class="onboarding-text-block">\n            <h3>\n                What is Scientific Thinking?\n            </h3>\n            <p>\n                Every new invention or discovery is a result of scientific work. Scientific thinking also teaches you problem solving skills, and includes reasoning and critical thinking.\n            </p>\n        </div>\n    </div>\n    <div class="mascot">\n        <img class="mascot-image" src="/static/edx-theme/images/hera_mascot.png" alt="HERA-mascot" />\n    </div>\n</div>\n', verbose_name=b'First Page'),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='page_2',
            field=models.TextField(blank=True, default='<div class="onboarding-holder">\n    <div class="onboarding-content">\n        <h1>\n            HERA will help you learn Science.\n        </h1>\n        <div class="onboarding-content-columns">\n            <div class="onboarding-text-block">\n                <p>\n                    You will experiment with a simulation and observe the results, and then answer 10 questions. If you answer incorrectly, you can ask for help. You will need to use "lightning bolts" to buy help. You will start the lesson with 300 lightning bolts.\n                </p>\n                <p>\n                    Each question will offer three types of help: Rephrase, Break it down, Teach me.\n                </p>\n                <p>\n                    If you answer incorrectly, you can try a new answer up to two more times.\n                </p>\n            </div>\n            <ul class="onboarding-list-block">\n                <li class="onboarding-list-item">\n                    <div class="mascoted">\n                        <img class="mascoted-image" src="/static/edx-theme/images/masct_1.png" alt="HERA-mascot-1" />\n                    </div>\n                    <div class="onboarding-list-item-text">\n                        Click <span class="colored-1">Rephrase</span> for a new version of the question.\n                        <br>\n                        <span class="hint">\n                        Cost is 10 lightning bolts!\n                    </span>\n                    </div>\n                </li>\n                <li class="onboarding-list-item">\n                    <div class="mascoted">\n                        <img class="mascoted-image" src="/static/edx-theme/images/masct_2.png" alt="HERA-mascot-2" />\n                    </div>\n                    <div class="onboarding-list-item-text">\n                        Click <span class="colored-2">Break it down</span> to see the first step needed.\n                        <br>\n                        <span class="hint">\n                        Cost is 20 lightning bolts!\n                    </span>\n                    </div>\n                </li>\n                <li class="onboarding-list-item">\n                    <div class="mascoted">\n                        <img class="mascoted-image" src="/static/edx-theme/images/masct_3.png" alt="HERA-mascot-3" />\n                    </div>\n                    <div class="onboarding-list-item-text">\n                        Click <span class="colored-3">Teach me</span> to learn more about the skill, and to see an example.\n                        <br>\n                        <span class="hint">\n                        Cost is 30 lightning bolts!\n                      </span>\n                    </div>\n                </li>\n            </ul>\n        </div>\n    </div>\n    <div class="mascot">\n        <img  class="mascot-image" src="/static/edx-theme/images/hera_mascot.png" alt="HERA-mascot" />\n    </div>\n</div>\n', verbose_name=b'Second Page'),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='page_3',
            field=models.TextField(blank=True, default='<div class="onboarding-holder">\n    <div class="onboarding-content">\n        <h1>\n            You will earn "atoms" for\n            <br>\n            correct answers!\n        </h1>\n        <div class="onboarding-text-block">\n            <p class="text-center">\n                Each question is worth 10 atoms, for up to 100 total atoms per lesson.\n                <br>\n                You can earn a badge at the end of the lesson based on your total atoms.\n                <br>\n                60 = Bronze&nbsp;&nbsp; |&nbsp;&nbsp; 70 = Silver&nbsp;&nbsp; |&nbsp;&nbsp; 80 = Gold&nbsp;&nbsp; |&nbsp;&nbsp; 90/100 = Platinum.\n                <br>\n                Use help when you need it, and see how high you can score!\n            </p>\n        </div>\n        <div class="onboarding-atoms-columns">\n            <div class="onboarding-atoms-column-item">\n                <div class="onboarding-atoms-icon">\n                    <img src="/static/edx-theme/images/atoms/icon_atom_1.png" alt="atom_icon1" />\n                    <span class="onboarding-atom-counter">\n                    300\n                  </span>\n                </div>\n                <p>\n                    Start with 300 lightning bolts to use if you need help\n                </p>\n            </div>\n            <div class="onboarding-atoms-column-item">\n                <div class="onboarding-atoms-icon">\n                    <img src="/static/edx-theme/images/atoms/icon_atom_2.png" alt="atom_icon2" />\n                    <span class="onboarding-atom-counter">\n                    100\n                  </span>\n                </div>\n                <p>\n                    Earn 10 atoms for each question.\n                </p>\n            </div>\n            <div class="onboarding-atoms-column-item">\n                <div class="onboarding-atoms-icon">\n                    <img src="/static/edx-theme/images/atoms/icon_atom_3.png" alt="atom_icon3" />\n                    <span class="onboarding-atom-counter">\n                    Gold\n                  </span>\n                </div>\n                <p>\n                    Convert atoms to a medal after each lesson!\n                </p>\n            </div>\n        </div>\n    </div>\n    <div class="mascot">\n        <img class="mascot-image" src="/static/edx-theme/images/hera_mascot.png" alt="HERA-mascot" />\n    </div>\n</div>\n', verbose_name=b'Third Page'),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='page_4',
            field=models.TextField(blank=True, default='<div class="onboarding-holder">\n    <div class="onboarding-content">\n        <h1>\n            If you need a break...\n        </h1>\n        <div class="onboarding-text-block">\n            <p class="text-center">\n                Try to complete each lesson in one session. If you have to stop in the middle of a lesson for longer than 30 minutes, you\'ll start at the beginning of that lesson when you come back.\n            </p>\n        </div>\n    </div>\n    <div class="mascot">\n        <img class="mascot-image" src="/static/edx-theme/images/hera_mascot.png" alt="HERA-mascot" />\n    </div>\n</div>\n', verbose_name=b'Fourth Page'),
        ),
    ]
