# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-03-02 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hera', '0004_auto_20200221_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScaffoldsSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_icon', models.ImageField(blank=True, null=True, upload_to=b'hera')),
                ('rephrase_cost', models.IntegerField(default=10)),
                ('rephrase_color', models.CharField(default=b'#257bba', max_length=7)),
                ('break_it_down_cost', models.IntegerField(default=20)),
                ('break_it_down_color', models.CharField(default=b'#674172', max_length=7)),
                ('teach_me_cost', models.IntegerField(default=30)),
                ('teach_me_color', models.CharField(default=b'#ec8b22', max_length=7)),
                ('starting_coins', models.IntegerField(default=300)),
            ],
            options={
                'verbose_name_plural': 'Scaffolds settings',
            },
        ),
    ]
