# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-03-03 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hera', '0005_scaffoldssettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedalsSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=b'hera/medals')),
                ('dna_icon', models.ImageField(upload_to=b'hera/medals', verbose_name=b'DNA icon')),
                ('min', models.PositiveSmallIntegerField()),
                ('max', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['min'],
                'verbose_name_plural': 'Medals settings',
            },
        ),
        migrations.AlterField(
            model_name='mascot',
            name='onboarding',
            field=models.ImageField(blank=True, null=True, upload_to=b'hera/mascots'),
        ),
        migrations.AlterField(
            model_name='mascot',
            name='user_dashboard',
            field=models.ImageField(blank=True, null=True, upload_to=b'hera/mascots'),
        ),
        migrations.AlterField(
            model_name='mascot',
            name='user_dashboard_modal',
            field=models.ImageField(blank=True, null=True, upload_to=b'hera/mascots'),
        ),
    ]
