# Generated by Django 4.2.18 on 2025-03-27 08:57

from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('course_to_library_import', '0003_remove_coursetolibraryimport_source_type_and_more'),
        ('content_staging', '0005_stagedcontent_version_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagedcontent',
            name='related_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_to_library_import.coursetolibraryimport'),
        ),
        migrations.AddField(
            model_name='stagedcontent',
            name='source_course_id',
            field=opaque_keys.edx.django.models.CourseKeyField(blank=True, db_index=True, help_text='ID of the imported course.', max_length=255, null=True, verbose_name='course ID'),
        ),
    ]
