# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-27 07:06
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tedix_ro', '0002_city_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message=b'Phone length should to be from 10 to 15', regex=b'^\\d{10,15}$')], verbose_name='phone')),
                ('classroom', models.CharField(choices=[(b'', b''), (b'7A', b'7A'), (b'7B', b'7B'), (b'7C', b'7C'), (b'7D', b'7D'), (b'8A', b'8A'), (b'8B', b'8B'), (b'8C', b'8C'), (b'8D', b'8D')], max_length=254, verbose_name='classroom')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tedix_ro.City')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tedix_ro.School')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
