# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-28 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tedix_ro', '0004_auto_20190327_0421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructorprofile',
            old_name='city',
            new_name='school_city',
        ),
        migrations.RenameField(
            model_name='parentprofile',
            old_name='city',
            new_name='school_city',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='city',
            new_name='school_city',
        ),
    ]
