# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-29 15:04
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tedix_ro', '0005_auto_20190328_0933'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='instructorprofile',
        #     name='school',
        # ),
        # migrations.RemoveField(
        #     model_name='instructorprofile',
        #     name='school_city',
        # ),
        # migrations.RemoveField(
        #     model_name='parentprofile',
        #     name='school',
        # ),
        # migrations.RemoveField(
        #     model_name='parentprofile',
        #     name='school_city',
        # ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message=b'The phone number length must be from 10 to 15 digits', regex=b'^\\d{10,15}$')], verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructorprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message=b'The phone number length must be from 10 to 15 digits', regex=b'^\\d{10,15}$')], verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parentprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message=b'The phone number length must be from 10 to 15 digits', regex=b'^\\d{10,15}$')], verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studentprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
