# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-03 19:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tedix_ro', '0007_studentprofile_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='classroom',
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message=b'The phone number length must be from 10 to 15 digits.', regex=b'^\\d{10,15}$')], verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message=b'The phone number length must be from 10 to 15 digits.', regex=b'^\\d{10,15}$')], verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message=b'The phone number length must be from 10 to 15 digits.', regex=b'^\\d{10,15}$')], verbose_name='phone'),
        ),
    ]
