# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-03 13:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tedix_ro', '0007_studentprofile_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message=b'The phone number length must be from 10 to 15 digits.', regex=b'^\\d{10,15}$')], verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message=b'The phone number length must be from 10 to 15 digits.', regex=b'^\\d{10,15}$')], verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom', to='tedix_ro.Classroom'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message=b'The phone number length must be from 10 to 15 digits.', regex=b'^\\d{10,15}$')], verbose_name='phone'),
        ),
    ]
