# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-08 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tedix_ro', '0009_auto_20190403_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tedix_ro.School'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='school_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tedix_ro.City'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tedix_ro.School'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='school_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tedix_ro.City'),
        ),
    ]
