# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-03 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('tedix_ro', '0010_auto_20190408_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourseDueDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='tedix_ro.InstructorProfile'),
        ),
        migrations.AddField(
            model_name='studentcourseduedate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_due_dates', to='tedix_ro.StudentProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='studentcourseduedate',
            unique_together=set([('student', 'course_id')]),
        ),
    ]
