# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-08 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tedix_ro', '0011_auto_20190503_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourseduedate',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
