# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-18 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tedix_ro', '0012_auto_20190508_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tedix_ro.City'),
        ),
    ]
