# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-12 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tedix_ro', '0013_school_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[(b'Public', b'Public'), (b'Private', b'Private')], default='Public', max_length=55),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='tedix_ro.City'),
        ),
    ]
