# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-18 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tedix_ro', '0014_auto_20190712_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='school',
            unique_together=set([('name', 'city')]),
        ),
    ]
