# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-12-10 16:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tedix_ro', '0016_auto_20190912_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReportSending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(max_length=255)),
                ('grade', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stident_report_sending', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([]),
        ),
    ]
