# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-08-12 15:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0014_courseoverview_certificate_available_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tedix_ro', '0017_auto_20191210_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourseReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', jsonfield.fields.JSONField(blank=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reports', to='course_overviews.CourseOverview')),
            ],
        ),
        migrations.RemoveField(
            model_name='studentreportsending',
            name='grade',
        ),
        migrations.AddField(
            model_name='studentcourseduedate',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_due_dates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='studentcourseduedate',
            unique_together=set([]),
        ),
        migrations.AddField(
            model_name='studentcoursereport',
            name='course_due_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_reports', to='tedix_ro.StudentCourseDueDate'),
        ),
        migrations.AddField(
            model_name='studentcoursereport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reports', to='tedix_ro.StudentProfile'),
        ),
    ]
