# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-08 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_email', '0006_course_mode_targets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseemail',
            name='from_addr',
            field=models.CharField(default='no-reply@example.com', max_length=255, null=True),
        ),
    ]
