# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-05 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopage',
            name='page',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
