# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-02-22 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_groups', '0003_auto_20170609_1455'),
        ('student', '0016_coursenrollment_course_on_delete_do_nothing'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cohort_leader',
            field=models.ManyToManyField(blank=True, to='course_groups.CourseCohort'),
        ),
    ]
