# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-07 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_auto_20191024_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='specialization',
            field=models.ManyToManyField(blank=True, to='student.Specialization'),
        ),
    ]
