# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-21 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_usersites_site_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersites',
            name='takamol_admin',
            field=models.BooleanField(default=False),
        ),
    ]
