# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-12-19 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_auto_20191107_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='has_diploma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='diploma_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
