# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-16 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='role',
        ),
        migrations.AddField(
            model_name='role',
            name='role',
            field=models.ManyToManyField(to='student.Specialization'),
        ),
    ]
