# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-22 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_auto_20191016_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='role',
        ),
        migrations.AddField(
            model_name='role',
            name='has_specialization',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='specialization',
            field=models.ManyToManyField(blank=True, null=True, to='student.Specialization'),
        ),
    ]
