# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-22 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_auto_20191022_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='specialization',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='specialization',
            field=models.ManyToManyField(blank=True, null=True, to='student.Specialization'),
        ),
    ]
